apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-isl2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-isl2
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-isl2
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-isl2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-isl2
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-qjhv-tenant/rhtap-demo-app/hacbs-test-project-isl2@sha256:c900250443aa5be6334a051f51faee79598ca396548ef545096aeff9f0a8c8ce
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
