apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-isl2
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-qjhv-tenant/rhtap-demo-app/hacbs-test-project-isl2@sha256:c900250443aa5be6334a051f51faee79598ca396548ef545096aeff9f0a8c8ce
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
