apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-isl2
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-qjhv-tenant/rhtap-demo-app/hacbs-test-project-isl2@sha256:0aff4845871760a171e8fdcde6d4bea40a5cd1c15c973f2f0dda08a4fa3c4230
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
